# -*- coding: utf-8 -*-
"""Exo_Traduction_automatique.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16R7yOgT5-noSLuDvrXlLkB0Bw76RpImv

#Machine Translation Project

This project explores the use of different language models for machine translation, including both sequence-to-sequence models and an autoregressive model. As machine translation systems become increasingly widespread, evaluating the quality of generated translations is essential to ensure their reliability.

Human evaluation is often considered the gold standard, assessing aspects such as adequacy (preservation of meaning) and fluency (naturalness of the output). However, it is time-consuming, resource-intensive, and inherently subjective.

To address these limitations, this project focuses on automatic evaluation methods, which provide more consistent and scalable assessments. These include metrics based on edit distance (e.g., WER), n-gram overlap (e.g., BLEU), and semantic similarity (e.g., BERTScore).

The study compares the performance of three models: two sequence-to-sequence models (Helsinki-NLP/opus-mt-en-fr and google/flan-t5-large) and one autoregressive model (openai/gpt-oss-120b), analyzing their translation quality using standard evaluation metrics.

Translation is from english to french. 20 sentences are randomly selected in a file (sent.csv) and fed to the models for translation.
"""

#random selection of 20 sentences for translation
import csv
import random

COUNT = 20

with open(f'sents.csv', newline="", encoding="utf8") as f:
  reader=list(csv.reader(f))
  header,rows=reader[0],reader[1:]

sample=random.sample(rows,COUNT)

with open(f'sents_sample_{COUNT}.csv','w',newline="", encoding="utf-8") as f:
  writer=csv.writer(f)
  writer.writerow(header)
  writer.writerows(sample)

"""###Translation with Helsinki-NLP/opus-mt-en-fr"""

#translation with Helsinki-NLP/opus-mt-en-fr
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer_helsinki = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-en-fr")
model_helsinki = AutoModelForSeq2SeqLM.from_pretrained("Helsinki-NLP/opus-mt-en-fr")

import re
import pandas as pd

refs=[]
traduction=[]
with open("sents_sample_20.csv", newline="", encoding="utf8") as f:
  lines=list(csv.reader(f))
  row=lines[1:]
  for i in row:
    inputs=tokenizer_helsinki(i[0],return_tensors="pt")
    translation_ids=model_helsinki.generate(**inputs)
    translation=tokenizer_helsinki.decode(translation_ids[0],skip_special_tokens=True)
    #Removal of non-breaking spaces as they are present in the references
    clean=re.sub("\xa0"," ",i[1])
    clean=re.sub("\u2009","",clean)
    refs.append(clean)
    traduction.append(translation)

refs

traduction

"""Transform sample sentences file to dataframe in order to better integrate generated translations"""

phrases_df=pd.read_csv("sents_sample_20.csv")

phrases_df["traduction_helsinki"]=traduction

phrases_df

"""###Evaluation of Helsinki-NLP/opus-mt-en-fr's translations

Evaluation with BLEU
"""

!pip install sacrebleu jiwer pymeteor evaluate bert_score

import sacrebleu
from sacrebleu.metrics import BLEU

"""To calculate the average of the different scores, the scores returned by each metric were normalized  since a simple average would be biased. For example, with WER, the farther the score is from 1, the better the translation, whereas with BLEU it is the opposite (the closer the score is to 1, the better the translation)."""

bleu=BLEU(max_ngram_order=4)
res=bleu.corpus_score(traduction,[refs])
score_bleu_helsinki=res.score
print(f'score bleu helsinki: {score_bleu_helsinki}')
score_bleu_helsinki_norm=score_bleu_helsinki/100
print(f'score bleu normalized: {score_bleu_helsinki_norm}')

"""Evaluation with WER"""

#Evaluation with WER
from jiwer import wer
wer_helsinki=wer(traduction,refs)
wer_helsinki_norm=1-wer_helsinki
print(f'Score wer_helsinki: {wer_helsinki}')
print(f'score wer helsinki normalisé: {wer_helsinki_norm}')

"""Evaluation with BERTScore"""

#Evaluation with BERTScore
from evaluate import load
bertscore=load("bertscore")
results=bertscore.compute(predictions=traduction,references=refs,lang="fr")["precision"]

results

mean_precision_helsinki=mean(results)
print(f'Moyenne de la précision: {mean_precision_helsinki}')

#Computation of the normalized overall score across the three evaluation metrics for Helsinki
score_moyen_helsinki=score_bleu_helsinki_norm+wer_helsinki_norm+mean_precision_helsinki/3
score_moyen_helsinki

"""###Translation with openai/gpt-oss-120b:free"""

import requests, json

trans_dict={}
with open("sents_sample_20.csv", newline="", encoding="utf8") as f:
  lines_autoreg=list(csv.reader(f))
  row_autoreg=lines_autoreg[1:]
  for i in row_autoreg:
    response = requests.post(
    url="https://openrouter.ai/api/v1/chat/completions",
    headers={
            "Authorization": "Bearer sk-or-v1-####",
            "Content-Type": "application/json",
          },
    data=json.dumps({ "model": "openai/gpt-oss-120b:free",
                            "messages": [ { "role": "user",
                                          "content": f'''Translate the following text from english to french. For each translation,
                                          respond in the form of a valid json object following this format:
                                          There should be no text before or after, simply follow this format.
                                          {{"english": "...",
                                           "french": "..."}}
                                           The sentences are from diverse domains: astronomy, chemistry, daily life and others:: {i[0]}''' }
                                        ], }))

    response=response.json()
    if "choices" in response:
      content=response['choices'][0]['message']["content"]
      try:
        data=json.loads(content)
        trans_dict[data["english"]]=data["french"]
      except json.JSONDecodeError:
        print("json invalide",content)
      print(response['choices'][0]['message']["content"])
    else:
        print(f'Erreur: {response}')

trans_dict.values()

traductions_api=[]
for i in trans_dict.values():
  traductions_api.append(i)
traductions_api

phrases_df["traduction_gpt"]=traductions_api

phrases_df

"""###Evaluation of openai/gpt-oss-120b:free's translations

With BLEU
"""

#BLEU
score_bleu2=bleu.corpus_score(traductions_api,[refs])
score_bleu_gpt=score_bleu2.score
score_bleu_gpt_norm=score_bleu_gpt/100
print(f"score bleu gpt: {score_bleu_gpt}")
print(f"score bleu gpt normalisé: {score_bleu_gpt_norm}")

#WER
wer_gpt=wer(traductions_api,refs)
wer_gpt_norm=1-wer_gpt
print(f"score wer gpt: {wer_gpt}")
print(f"score wer gpt normalisé: {wer_gpt_norm}")

results_gpt=bertscore.compute(predictions=traductions_api,references=refs,lang="fr")["precision"]

results_gpt

mean_precision_gpt=mean(results_gpt)
print(f'precision moyenne gpt: {mean_precision_gpt} ')

#Computation of the normalized overall score across the three evaluation metrics for openai/gpt-oss-120b:free
score_moyen_gpt=score_bleu_gpt_norm+wer_gpt_norm+mean_precision_gpt/3
score_moyen_gpt

"""###Translation with google/flan-t5-large"""

!pip install -U transformers accelerate

from transformers import T5Tokenizer, T5ForConditionalGeneration

tokenizer_google=T5Tokenizer.from_pretrained("google/flan-t5-large")
model_google=T5ForConditionalGeneration.from_pretrained("google/flan-t5-large").to("cuda")

reference=[]
translation=[]
with open("sents_sample_20.csv", newline="", encoding="utf8") as f:
  lines=list(csv.reader(f))
  row_google=lines[1:]
  for i in row_google:
    nettoy=re.sub("\xa0","",i[1])
    nettoy=re.sub("\u2009","",nettoy)
    reference.append(nettoy)
    input_text=f'Translate from english to french {i[0]}'
    input_ids=tokenizer_google(input_text,return_tensors="pt").input_ids.to("cuda")
    outputs=model_google.generate(input_ids,max_length=100)
    out=tokenizer_google.decode(outputs[0], skip_special_tokens=True)
    translation.append(out)
    print(out)

reference

translation

phrases_df["traduction_google"]=translation

phrases_df

phrases_df.to_csv("samples_traductions.csv")

"""###Evaluation of de google/flan-t5-large's translations

Evaluation wuth BLEU
"""

#BLEU
score_bleu3=bleu.corpus_score(translation,[reference])
score_bleu_google=score_bleu3.score
score_bleu_google_norm=score_bleu_google/100
print(f'score bleu google: {score_bleu_google}')
print(f'score bleu google normalisé: {score_bleu_google_norm}')

"""Evaluation with WER"""

#WER
wer_google=wer(translation,reference)
wer_google_norm=1-wer_google
print(f'score wer google: {wer_google}')
print(f'score wer google normalisé: {wer_google_norm}')
print(wer_google)

"""Evaluation with BERTScore"""

result_google=bertscore.compute(predictions=translation,references=reference,lang="fr")["precision"]
result_google

#mean score for google/flan-t5-large
mean_precision_google=mean(result_google)

#Computation of the normalized overall score across the three evaluation metrics for google/flan-t5-large
score_moyen_google=score_bleu_google_norm+wer_google_norm+mean_precision_google/3
score_moyen_google

print(f'Score moyen pour le modèle helsinki: {score_moyen_helsinki}')
print(f'Score moyen pour le modèle gpt: {score_moyen_gpt}')
print(f'Score moyen pour le modèle google: {score_moyen_google}')

"""##Results and analysis

Overall, the results returned by all models are acceptable, even though there are sometimes mistranslations. The translations produced by Helsinki-NLP/opus-mt-en-fr are satisfactory and sometimes very close to the reference, as in the first sentence (ref:Décorez votre chez-vous pour les fêtes avec ces lumières festives”), with Helsinki’s suggestion: “Décorez votre maison pour les vacances avec ces lumières festives” The same applies to openai/gpt-oss-120b:free, which produces for the same sentence: “Décorez votre maison pour les fêtes avec ces lumières festives.” A difference lies in the evaluative noun phrase “your home,” which is used in the reference translation. However, the translations differ regarding the English term “holidays,” which the reference translates as “les fêtes,” as does the GPT model, while Helsinki translates it as “les vacances.” As for the Google model, it makes an error in distinguishing between “lights” and “stars,” and proposes: “Decorate your home for the holidays with these festive stars.”
"""